# Local build/run helper (Windows PowerShell).
# Does the SAME steps CI does, so local output matches the cloud build.
#
#   .\tool\local.ps1            # build a debug APK and print its path
#   .\tool\local.ps1 run        # flutter run to the connected emulator/device
#                                 (hot reload — fastest iteration)
#   .\tool\local.ps1 apk        # build a release-mode (debug-signed) APK
#
# Requires Flutter + Android SDK + JDK17 on PATH (see README / install steps).
# android/ is generated by `flutter create` (idempotent, won't touch lib/),
# then the manifest + gradle patches are applied just like in CI.

param([string]$mode = "debug")

$ErrorActionPreference = "Stop"
Set-Location (Split-Path $PSScriptRoot -Parent)

Write-Host "==> flutter create (generate android/ if missing)" -ForegroundColor Cyan
flutter create . --org com.infoshare --project-name info_share_app --platforms=android

Write-Host "==> patch AndroidManifest" -ForegroundColor Cyan
python tool/patch_manifest.py

Write-Host "==> patch Gradle (compileSdk 36)" -ForegroundColor Cyan
python tool/patch_gradle.py

Write-Host "==> flutter pub get" -ForegroundColor Cyan
flutter pub get

switch ($mode) {
  "run" {
    Write-Host "==> flutter run (hot reload; press r to reload, R to restart, q to quit)" -ForegroundColor Green
    flutter run
  }
  "apk" {
    Write-Host "==> flutter build apk --release" -ForegroundColor Green
    flutter build apk --release
    Write-Host "APK: build\app\outputs\flutter-apk\app-release.apk" -ForegroundColor Yellow
  }
  default {
    Write-Host "==> flutter build apk --debug" -ForegroundColor Green
    flutter build apk --debug
    Write-Host "APK: build\app\outputs\flutter-apk\app-debug.apk" -ForegroundColor Yellow
  }
}
